accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sign_up/', views.sign_up, name='sign_up'),
]

fiend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('redditsearch.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('redditsearch.urls'))
]

# urlpatterns += staticfiles_urlpatterns()

redditsearch/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('test/', views.test, name='test'),
    path('redditsearch/', views.reddit_search, name='reddit_search'),
    path('delete/<str:id>', views.search_delete, name='search_delete'),
    path('layout/', views.layout, name='layout'),

]

accounts/models.py
from django.db import models

# Create your models here.

redditsearch/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Search(models.Model):
    searchname = models.CharField(max_length=128)
    subreddits = models.CharField(max_length=1024)
    searchterms = models.CharField(max_length=2048)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='searches')

    def __str__(self):
        return self.searchname

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


def sign_up(request):
    if request.method == 'POST':
        # Store the data from the POST request
        form = UserCreationForm(request.POST)

        # If the form is valid (eg. user's username is unique)
        if form.is_valid():
            # Save the user into the database
            user = form.save()
            login(request, user)

            return redirect('/dashboard/test/')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required
def profile(request):
    return render(request, '/redditsearch/dashboard.html')

redditsearch/views.py
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, render
import praw
import os
import json
from .models import Search
from django.contrib.auth.decorators import login_required

# Create your views here.


class RedditPost:
    def __init__(self, forum, submission):
        self.subreddit = forum
        self.title = submission.title
        self.score = submission.score
        self.comments = submission.num_comments
        self.link = submission.permalink
        self.date = submission.created_utc
        self.body = submission.selftext
        self.id = submission.id
        self.weight = 0
        self.contains = []

    def __hash__(self):
        return hash(self.id + str(self.date))


def find_matches(subreddits, searchterms):
    r = praw.Reddit(user_agent=os.getenv('USER_AGENT'),
                    client_id=os.getenv('CLIENT_ID'), client_secret=os.getenv('CLIENT_SECRET'))

    posts = set()

    for subreddit in subreddits:
        sr = r.subreddit(subreddit)
        for submission in sr.hot(limit=100):
            if not submission.selftext:
                continue

            found = False
            for term in searchterms:
                if term in submission.title.casefold() or term in submission.selftext.casefold():
                    found = True

            if found:
                posts.add(RedditPost(subreddit, submission))
    return posts


def score_posts(posts, searchterms):
    maxscore = 1
    mostrecent = 1
    mostcomments = 1
    for post in posts:
        if post.score >= maxscore:
            maxscore = post.score
        if post.date >= mostrecent:
            mostrecent = post.date
        if post.comments >= mostcomments:
            mostcomments = post.comments
        for term in searchterms:
            if term in post.body.casefold() or term in post.title.casefold():
                post.contains.append(term)

    for post in posts:
        post.weight = (len(post.contains) / len(searchterms)) * .65
        post.weight += (post.score / maxscore) * .05
        post.weight += (post.date / mostrecent) * .25
        post.weight += (post.comments / mostcomments) * .05

    weighted_posts = sorted(
        posts, key=lambda x: x.weight, reverse=True)
    return weighted_posts


@login_required
def reddit_search(request):

    if request.method == 'POST':
        json_data = json.loads(request.body)
        Search.objects.create(
            searchname=json_data['searchname'],
            subreddits=json_data['subreddits'],
            searchterms=json_data['searchterms'],
            user=request.user,
        )

    searches = request.user.searches.all()

    results = []

    for search in searches:
        subreddits = search.subreddits.split(',')
        searchterms = search.searchterms.split(',')

        posts = find_matches(subreddits, searchterms)
        weighted_posts = score_posts(posts, searchterms)

        json_formatted_results = []
        for post in weighted_posts:
            post = {
                'title': post.title,
                'link': 'http://reddit.com' + post.link,
                'subreddit': post.subreddit,
                'matches': post.contains,
                'date': post.date,
                'score': int(post.weight * 100),
                'postid': post.id,
            }
            json_formatted_results.append(post)
        results.append({
            'searchname': search.searchname,
            'subreddits': ','.join(subreddits),
            'searchterms': ','.join(searchterms),
            'posts': json_formatted_results,
            'hits': len(json_formatted_results),
            'id': search.id,
        })

    return JsonResponse(results, safe=False)
    # return render(request, 'redditsearch/searchresults.html', {'results': results})


def search_delete(request, id):
    search = get_object_or_404(Search, id=id)
    search.delete()
    return JsonResponse({})


def edit_search(request, id):
    search_delete(request, id)
    reddit_search(request)


@login_required
def dashboard(request):
    return render(request, 'redditsearch/dashboard.html')


@login_required
def test(request):
    return render(request, 'redditsearch/test.html')


def layout(request):
    return render(request, 'layout.html')

def welcome(request):
    return render(request, 'redditsearch/welcome.html')

redditsearch/templates/redditsearch/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel='stylesheet' type='text/css' href='https://necolas.github.io/normalize.css/8.0.1/normalize.css'>
  <link rel='stylesheet' href="{% static 'css/site.css'%}">
  <title>Fiend</title>
</head>

<body>

  {% if user.is_authenticated %}
  {{ user.username }} <a href="{% url 'accounts:logout' %}">Log Out</a>
  {% else %}
  <a href="{% url 'accounts:login' %}">Log In</a>
  <a href="{% url 'accounts:sign_up' %}">Sign Up</a>
  {% endif %}


  <div id="app" v-cloak>
    <div class="la-ball-atom la-dark" v-if='loading'>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>

    <button v-on:click='addsearch=true' v-if='loading==false'>New Search</button>
    <div v-if='addsearch'>
      <form @submit.prevent='createsearch()'>
        <div>Search Name: <input type="text" v-model="nsearchname"></div>
        <div>Subreddits to search: <input type="text" v-model='nsubreddits'></div>
        <div>Search terms: <input type="text" v-model='nsearchterms'></div>
        <div><button v-on:click='loading=true, addsearch=false'>Submit</button></div>
      </form>
      <button v-on:click='addsearch=false'>Cancel</button>
    </div>

    <br><br>

    <div v-for='(result, index) in results'>
      <div>
        <div v-on:click='result.display = !result.display'>Search: [[ result.searchname ]] <br>Results: [[ result.hits ]]</div>
        <button v-on:click='result.edit=true'>Edit</button><button v-on:click='deletesearch(result.id, index)'>Delete</button>
        <ul v-if='result.display'>
          <li v-for='post in result.posts'>[[ post.score ]] | <a :href='post.link' target='_blank'>[[ post.title ]]</a></li>
        </ul>
        <div v-if='result.edit'>
          <form @submit.prevent='editsearch(result, index)'>
            <div>Search Name: <input type="text" v-model='result.searchname'></div>
            <div>Subreddits to search: <input type="text" v-model='result.subreddits'></div>
            <div>Search terms: <input type="text" v-model='result.searchterms'></div>
            <input type='hidden' v-model:value='result.id'><input type='hidden' v-model='index'>
            <div><button>Submit</button></div>
          </form>
        </div>
      </div>
      <br><br>
    </div>

  </div>


  <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js'></script>


  <script src='{% static "js/dashboard.js"%}'></script>
</body>

</html>

redditsearch/templates/redditsearch/searchresults.html
<html>

<head>
  <link rel='stylesheet' type='text/css' href='https://necolas.github.io/normalize.css/8.0.1/normalize.css'>
</head>

<body>
  {{ user.username }}

  {% for result in results %} <h1>{{ result.searchname }}</h1>
  Score | Post
  {% for post in result.posts %}
  <p>{{ post.score }} | <a href='{{post.link }}' target="_blank">{{ post.title }}</a></p>
  {% endfor %}
  {% endfor %}
</body>

</html>

redditsearch/templates/redditsearch/test.html
{% extends 'layout.html' %}


{% block content %}
<div id='app'>

  <div class='button'>
    <div @click='addsearch=!addsearch' class='newsearch'>Create New Search</div>
  </div>
  <div class='search-content' :class='{collapsed:addsearch}'>
    <div class='search-item card'>
      <form @submit.prevent='createsearch()'>
        <div>Search Name: <input type="text" v-model="nsearchname"></div>
        <div>Subreddits to search: <input type="text" v-model='nsubreddits'></div>
        <div>Search terms: <input type="text" v-model='nsearchterms'></div>
        <div><button v-on:click='loading=true, addsearch=false'>Submit</button></div>
      </form>
    </div>
  </div>


  <div v-for='(result, index) in results' class='all-searches'>
    <div class='scroll'>
      <div><img src='/static/img/scrollknob.png'></div>
      <div class='search-header'>
        <div class='title'>[[ result.searchname ]]</div>
        <div class='search-utility'>
          <div class='search-action' @click='result.edit=!result.edit'>edit</div>
          <div class='search-action' @click='deletesearch(result.id, index)'>delete</div>
          <div class='search-action' @click='result.display=!result.display'>
            <div class='result-count'>[[ result.hits ]]</div>
            <div :class='{"drop-down": result.display}'>^</div>
          </div>
        </div>
      </div>
      <div><img src='/static/img/scrollend2.png'></div>
    </div>
    <div class='search-content' :class='{collapsed:result.edit}'>
      <div class='search-item card'>
        <form @submit.prevent='editsearch(result, index)'>
          <div>Search Name: <input type="text" v-model='result.searchname'></div>
          <div>Subreddits to search: <input type="text" v-model='result.subreddits'></div>
          <div>Search terms: <input type="text" v-model='result.searchterms'></div>
          <input type='hidden' v-model:value='result.id'><input type='hidden' v-model='index'>
          <div><button>Submit</button></div>
        </form>
      </div>
    </div>

    <div v-for='post in result.posts'>
      <div class='search-content' :class='{collapsed:result.display}'>
        <div class='search-item card'>
          <div class='score'>[[ post.score ]]</div>
          <div class='post-title'>[[ post.title ]]... </div>
          <!-- post.title.slice(0,64) -->
          <div class='link'><a :href='post.link' target='_blank'>~go~</a></div>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

redditsearch/templates/redditsearch/welcome.html
{% extends 'layout.html' %}

{% block style %}
<style>
  .welcome {
    background: #FFE0AB;
    margin: 10vh auto;
    width: 90%;
    padding: 1em;
    border-radius: 10px;
  }
</style>

{% endblock style%}

{% block content %}
<div class='welcome'>
  <p>FIEND, (Fi)nd (En)gage (D)eliver, enables organizations to locate niche online communities whose users interests
    align with the organizations goals. FIEND uses a custom algorithm to search subreddits
    for specific searchterms and then rank the results based on relevancy, timeliness, and
    engagement from the community.</p>

  How it works:
  <ul>
    <li>1. Select what subreddits you would like to search</li>
    <li>2. Decide what you'd like to search form</li>
    <li>3. Sit back and watch as your results come in</li>
  </ul>
  <p>Results are updated everytime you visit your dashboard!</p>

  <p><a href="{% url 'accounts:sign_up' %}">Sign-up</a> and give it a try!</p>
</div>
{% endblock content %}

templates/accounts/login.html
{% extends "layout.html" %}

{% block content %}
<div class='login-or-signup'>
  <div style='background: #FFE0AB;'>
    Login
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Log In</button>
    </form>
  </div>
  <div>
    {% endblock content %}

templates/accounts/profile.html
{% extends "layout.html" %}

{% block content %}
    <h1>Welcome to Refrosher</h1>
    {{ user.username }}
{% endblock content %}

templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block content %}
<div style='background: #FFE0AB;'>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Sign Up</button>
  </form>
</div>
{% endblock content %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Fiend</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='stylesheet' href='https://necolas.github.io/normalize.css/8.0.1/normalize.css'>
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css"> -->
  <link rel='stylesheet' href='{% static "css/style.css" %}'>
  <link href="https://fonts.googleapis.com/css?family=Dawning+of+a+New+Day|Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Courgette|Dawning+of+a+New+Day|Neucha|Open+Sans|Roboto" rel="stylesheet">


  {% block style %}

  {% endblock style %}

  <style>
    @@font-face {
      font-family: 'victorian';
      src: url('{% static "fonts/GreatVictorian-Standard.orf" %}')
    }

    body {
      background-image: url('{% static "img/wallpapers.jpg" %}');
      background-size: 100%;
    }

    .nav {
      display: flex;
      background-image: url('{% static "img/moulding.jpg" %}');
      background-size: contain;
      /* background: #0E2B5B; */
      padding: .5vw;
    }

    .nav-element {

      color: black;
      font-weight: bold;
      padding-right: 1em;
    }

    .nav-element a {
      text-decoration: none;
      color: black;
      font-weight: bold;
      background: white;
      border-width: 5px;
      padding: .1em;
      font-family: 'Cinzel Decorative';
      border-color: #b29600;
      border-style: double;

    }

    .logo {
      display: flex;
      justify-content: flex-end;
      background-image: url('{% static "img/panels.jpg" %}');
      /* background: #53BBFF; */
      padding: .3vh;
      color: #ffcc00;
      padding-right: 3vw;
      font-family: 'Cinzel Decorative';
    }

    .logo-main {
      font-family: 'Cinzel Decorative';
      padding-left: 1vw;
      padding-right: 1vw;
      font-size: 8vh;
      transform: skew(-15deg)
    }

    .login-or-signup {
      display: flex;
      width: 50vw;
      margin: auto;
      padding: 10vh;

    }
  </style>
</head>

<body>

  <nav>
    <div class='nav'>
      <div class='nav-element'>
        <a href='/dashboard/test'> Home </a>
      </div>
      <div class='nav-element'>
        {% if user.is_authenticated %} <a href="{% url 'accounts:logout' %}">Log Out</a>
        | {{ user.username }}
      </div>
      <div class='nav-element'>
        {% else %}
        <a href="{% url 'accounts:login' %}">Log In</a>
      </div>
      <div class='nav-element'>
        <a href="{% url 'accounts:sign_up' %}">Sign Up</a>
        {% endif %}
      </div>
    </div>
    <div class='logo'>
      <div><img src='{% static "img/goldholmes.svg" %}' width='50'> </div>
      <div class='logo-main'>F I E N D</div>
      <div class='logo-sub'></div>
    </div>
  </nav>


  <div class="content">
    {% block content %}
    {% endblock content %}
  </div>


  <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js'></script>
  <script src='{% static "js/vue.js"%}'></script>
</body>

</html>